### ISSUE TITLE
Possible to add Field meta Data ?

### ISSUE THREAD

**Issue by gognamunish** [pwall567/json-kotlin-schema-codegen#20]
Hi - is it possible to extend the code generation to include some meta data so that generated model can be used to build data dictionary or run time behaviour ??

e.g. 

@FeildMetaData(encrypted=true, blabla=[])
val someField : String

Thanks.

**Comment by pwall567** [comment]
Hi Munish, have you seen the [`annotations`](https://github.com/pwall567/json-kotlin-schema-codegen/blob/main/CONFIG.md#annotations) section of the Configuration Guide?

It seems to me that this would cover exactly what you're asking for here.  Annotations can be added to the class or to each field, and the content can be generated from a Mustache template with access to a number of details about the class or field.

Regards, Peter

**Comment by gognamunish** [comment]
Thank you I missed it earlier. 
This is what I was exactly looking for 🙏
