### ISSUE TITLE
Schema that specifies long min/max results in uncompilable code

### ISSUE THREAD

**Issue by myronmarston** [pwall567/json-kotlin-schema-codegen#6]
We have some JSON schemas that explicitly specify the min/max values for all numeric fields.  In a few cases, the min/max are just the min/max of a `Long`.  This library produces an initialization check like:

``` kotlin
    init {
        require(someLongField in -9223372036854775808L..9223372036854775807L) { "someLongField not in range -9223372036854775808..9223372036854775807 - $someLongField" }
    }
```

However, this code does not compile, because while `-9223372036854775808L` is a valid `Long` value, [Kotlin doesn't currently support it as a literal](https://youtrack.jetbrains.com/issue/KT-17172) (since it compiles to `9223372036854775808L * -1` and `9223372036854775808L` is larger than `Long.MAX_VALUE`).

For now, I'm working around this by replacing the long min/max values with a reference to the `Long.MIN_VALUE` and `Long.MAX_VALUE` constants, but it'd be nice to not have to work around this and it seems like a bug for this library to generate uncompilable code.

Could the library detect and work around this case?  You could either replace the literals with constant references (as I'm doing) or maybe even omit the initialization check altogether--in this case, it's not possible to have a long value outside this range.

**Comment by pwall567** [comment]
Hi Myron - thanks for this.

I have a fix that does exactly what you suggest - don't test for minimum and maximum when the values are the MIN_VALUE or MAX_VALUE for the type.

Expect a new version in the next day or so.

**Comment by pwall567** [comment]
OK - version 0.36 now in Maven Central.  Let me know if you still have problems.

**Comment by myronmarston** [comment]
Thanks @pwall567 -- I confirmed your fix is working for me!
