### ISSUE TITLE
MULTIPLE_DECIMAL for Kotlin generates a compile error: Operator '==' cannot be applied to 'BigDecimal' and 'Int'

### ISSUE THREAD

**Issue by ehowarth** [pwall567/json-kotlin-schema-codegen#9]
Input:

    "price": {
        "type": "number",
        "multipleOf": 0.01
    }

Actual:

    require(price.rem(cg_dec0) == 0) { "price not a multiple of 0.01 - $price" }

Expected:

    require(price.rem(cg_dec0).compareTo(BigDecimal.ZERO) == 0) { "price not a multiple of 0.01 - $price" }

**Comment by pwall567** [comment]
Hi, thanks for finding this – and for providing an excellent fix for it.  And for providing a test – I'm embarrassed that I hadn't tested for this usage.

**Comment by pwall567** [comment]
This made me look again at the code generated for `multipleOf` and I found an error in the code for `Long` as well.  Your fix and this other fix are in version 0.77.

Thanks again.

**Comment by ehowarth** [comment]
Thanks. Well-structured code is easy to modify.

I use this via json-kotlin-maven. Is it OK to update the versions there?

**Comment by pwall567** [comment]
I was just about to do that.  Expect an update in a few minutes.

**Comment by pwall567** [comment]
OK, version 0.77 of the Maven plugin has been uploaded – should appear in Maven Central shortly.

Good to hear someone is using the Maven plugin – I get more feedback on the Gradle plugin, so the Maven one doesn't get as much attention, and doesn't offer as much flexibility.  I'll put more effort into it now that I know it's being used.
